# Generated by Django 3.0.8 on 2021-03-30 06:29

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('CMSResources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcespage',
            name='content',
            field=wagtail.core.fields.StreamField([('articlecards', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add Title', required=True)), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Title', required=True)), ('author', wagtail.core.blocks.CharBlock(help_text='Author', required=True)), ('description', wagtail.core.blocks.TextBlock(help_text='Description', required=True)), ('article', wagtail.core.blocks.RichTextBlock(help_text='Article', required=True))])))])), ('imagecards', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add Title', required=True)), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Title', required=True)), ('description', wagtail.core.blocks.TextBlock(help_text='Description', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock())])))])), ('videocards', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add Title', required=True)), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add Title', required=True)), ('caption', wagtail.core.blocks.CharBlock(help_text='Caption', required=True)), ('video', wagtail.embeds.blocks.EmbedBlock(label='Video'))])))])), ('linkcards', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add Title', required=True)), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Title', required=True)), ('description', wagtail.core.blocks.TextBlock(help_text='Description', required=True)), ('link', wagtail.core.blocks.RichTextBlock(help_text='Resources Link', required=True))])))]))], blank=True, null=True),
        ),
    ]
