# Generated by Django 2.2.12 on 2021-03-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolcoordinator',
            name='contact',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='schoolcoordinator',
            name='personaladdress',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='schoolcoordinator',
            name='schoolname',
            field=models.CharField(max_length=2000),
        ),
    ]
