# Generated by Django 3.1.7 on 2021-03-07 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMChildParentsRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuid', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='smchildregistration',
            name='user',
        ),
        migrations.RemoveField(
            model_name='anganwadiworker',
            name='age',
        ),
        migrations.RemoveField(
            model_name='anganwadiworker',
            name='age_in_days',
        ),
        migrations.RemoveField(
            model_name='anganwadiworker',
            name='age_in_months',
        ),
        migrations.RemoveField(
            model_name='anganwadiworker',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='anganwadiworker',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='anganwadiworker',
            name='personaladdress',
        ),
        migrations.RemoveField(
            model_name='mukhyasevika',
            name='age',
        ),
        migrations.RemoveField(
            model_name='mukhyasevika',
            name='age_in_days',
        ),
        migrations.RemoveField(
            model_name='mukhyasevika',
            name='age_in_months',
        ),
        migrations.RemoveField(
            model_name='mukhyasevika',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='mukhyasevika',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='mukhyasevika',
            name='personaladdress',
        ),
        migrations.AddField(
            model_name='schoolcoordinator',
            name='age',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='schoolcoordinator',
            name='annualincome',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='schoolcoordinator',
            name='education',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='schoolcoordinator',
            name='occupation',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='schoolcoordinator',
            name='profilephoto',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='schoolcoordinator',
            name='schooladdress',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='schoolcoordinator',
            name='schoolcontact',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.DeleteModel(
            name='SMChildParentsDetails',
        ),
        migrations.DeleteModel(
            name='SMChildRegistration',
        ),
    ]
