# Generated by Django 3.1.5 on 2021-04-03 07:26

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodHabitsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Choose_your_dietary_habit', models.CharField(blank=True, choices=[('Please select:', 'Please select:'), ('I eat only vegetables. I DO NOT eat milk, eggs, chiken, mutton or fish. (Vegan)', 'I eat only vegetables. I DO NOT eat milk, eggs, chiken, mutton or fish. (Vegan)'), ('I eat only milk and vegetables. I DO NOT eat eggs, chicken, mutton, fish. (Lacto-Vegetarian)', 'I eat only milk and vegetables. I DO NOT eat eggs, chicken, mutton, fish. (Lacto-Vegetarian)'), ('I eat only eggs and vegetables. I DO NOT eat milk, chicken, mutton or fish. (Eggetarian)', 'I eat only eggs and vegetables. I DO NOT eat milk, chicken, mutton or fish. (Eggetarian)'), ('I eat milk, eggs and vegetables. I DO NOT eat chicken, mutton, fish.(Lacto-ova-vegetarian)', 'I eat milk, eggs and vegetables. I DO NOT eat chicken, mutton, fish.(Lacto-ova-vegetarian)'), ('I eat vegetables, milk, egg, chicken, mutton, fish. (Non-vegetarian)', 'I eat vegetables, milk, egg, chicken, mutton, fish. (Non-vegetarian)'), ('I eat vegetables, milk and fish. I DO NOT eat eggs, chicken and mutton. (Pescatarian)', 'I eat vegetables, milk and fish. I DO NOT eat eggs, chicken and mutton. (Pescatarian)')], max_length=100)),
                ('Choose_meals_consumed_in_a_day', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Breakfast', 'Breakfast'), ('Mid-morning snack', 'Mid-morning snack'), ('Lunch', 'Lunch'), ('Afternoon snack', 'Afternoon snack'), ('Evening snack', 'Evening snack'), ('Dinner', 'Dinner'), ('Bed-time snack', 'Bed-time snack'), ('Other', 'Other')], max_length=91)),
                ('other_meal', models.CharField(blank=True, max_length=1000)),
                ('breakfast', models.CharField(blank=True, max_length=1000)),
                ('lunch', models.CharField(blank=True, max_length=1000)),
                ('dinner', models.CharField(blank=True, max_length=1000)),
                ('snack', models.CharField(blank=True, max_length=1000)),
                ('canteen', models.CharField(blank=True, max_length=1000)),
                ('tiffin', models.CharField(blank=True, choices=[('Please select:', 'Please select:'), ('I carry my tiffin daily', 'I carry my tiffin daily'), ('I carry my tiffin only once a week', 'I carry my tiffin only once a week'), ('I carry my tiffin 2-3 times a week', 'I carry my tiffin 2-3 times a week'), ('I carry my tiffin more than 3 times a week', 'I carry my tiffin more than 3 times a week'), ('I never carry my tiffin', 'I never carry my tiffin')], max_length=100)),
                ('midday_meal', models.CharField(blank=True, choices=[('Please select:', 'Please select:'), ('Yes, I get it and I love it', 'Yes, I get it and I love it'), ('Yes, I get it but I dont Like it so I eat something else', 'Yes, I get it but I dont Like it so I eat something else'), ('No, I dont get Mid-day meal in my school', 'No, I dont get Mid-day meal in my school')], max_length=100)),
                ('soyabean', models.CharField(blank=True, choices=[('Please select:', 'Please select:'), ('Daily', 'Daily'), ('Thrice in a week', 'Thrice in a week'), ('Once in a week', 'Once in a week'), ('Twice in a month', 'Twice in a month'), ('Monthly', 'Monthly'), ('Never', 'Never')], max_length=100)),
                ('bananapeel', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=100)),
                ('bottlegourd', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NutriAnthropometricParametersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enter_your_weight', models.CharField(blank=True, max_length=100)),
                ('Enter_your_height', models.CharField(blank=True, max_length=100)),
                ('Enter_your_waist_circumference', models.CharField(blank=True, max_length=100)),
                ('Enter_your_hip_circumference', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
