# Generated by Django 3.0.8 on 2021-03-21 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anemiclactatingmother',
            old_name='birthdate',
            new_name='childbirthdate',
        ),
        migrations.RemoveField(
            model_name='anemiclactatingmother',
            name='ICDScenteraddress',
        ),
        migrations.RemoveField(
            model_name='anemiclactatingmother',
            name='ICDScentercontact',
        ),
        migrations.RemoveField(
            model_name='anemiclactatingmother',
            name='age',
        ),
        migrations.RemoveField(
            model_name='anemiclactatingmother',
            name='annualincome',
        ),
        migrations.RemoveField(
            model_name='anemiclactatingmother',
            name='bmi',
        ),
        migrations.RemoveField(
            model_name='anemiclactatingmother',
            name='education',
        ),
        migrations.RemoveField(
            model_name='anemiclactatingmother',
            name='foodhabits',
        ),
        migrations.RemoveField(
            model_name='anemiclactatingmother',
            name='height',
        ),
        migrations.RemoveField(
            model_name='anemiclactatingmother',
            name='heightunit',
        ),
        migrations.RemoveField(
            model_name='anemiclactatingmother',
            name='hip',
        ),
        migrations.RemoveField(
            model_name='anemiclactatingmother',
            name='hipunit',
        ),
        migrations.RemoveField(
            model_name='anemiclactatingmother',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='anemiclactatingmother',
            name='uploaded_photo',
        ),
        migrations.RemoveField(
            model_name='anemiclactatingmother',
            name='waist',
        ),
        migrations.RemoveField(
            model_name='anemiclactatingmother',
            name='waistunit',
        ),
        migrations.RemoveField(
            model_name='anemiclactatingmother',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='anemiclactatingmother',
            name='weightunit',
        ),
        migrations.RemoveField(
            model_name='anemiclactatingmother',
            name='whratio',
        ),
        migrations.RemoveField(
            model_name='anemiclactatingmother',
            name='whratioderived',
        ),
    ]
