# Generated by Django 3.0.8 on 2021-03-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20210321_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anemicpregnantwoman',
            name='ICDScenteraddress',
        ),
        migrations.RemoveField(
            model_name='anemicpregnantwoman',
            name='ICDScentercontact',
        ),
        migrations.RemoveField(
            model_name='anemicpregnantwoman',
            name='age',
        ),
        migrations.RemoveField(
            model_name='anemicpregnantwoman',
            name='annualincome',
        ),
        migrations.RemoveField(
            model_name='anemicpregnantwoman',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='anemicpregnantwoman',
            name='bmi',
        ),
        migrations.RemoveField(
            model_name='anemicpregnantwoman',
            name='education',
        ),
        migrations.RemoveField(
            model_name='anemicpregnantwoman',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='anemicpregnantwoman',
            name='foodhabits',
        ),
        migrations.RemoveField(
            model_name='anemicpregnantwoman',
            name='height',
        ),
        migrations.RemoveField(
            model_name='anemicpregnantwoman',
            name='heightunit',
        ),
        migrations.RemoveField(
            model_name='anemicpregnantwoman',
            name='hip',
        ),
        migrations.RemoveField(
            model_name='anemicpregnantwoman',
            name='hipunit',
        ),
        migrations.RemoveField(
            model_name='anemicpregnantwoman',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='anemicpregnantwoman',
            name='uploaded_photo',
        ),
        migrations.RemoveField(
            model_name='anemicpregnantwoman',
            name='waist',
        ),
        migrations.RemoveField(
            model_name='anemicpregnantwoman',
            name='waistunit',
        ),
        migrations.RemoveField(
            model_name='anemicpregnantwoman',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='anemicpregnantwoman',
            name='weightunit',
        ),
        migrations.RemoveField(
            model_name='anemicpregnantwoman',
            name='whratio',
        ),
        migrations.RemoveField(
            model_name='anemicpregnantwoman',
            name='whratioderived',
        ),
        migrations.AddField(
            model_name='anemicpregnantwoman',
            name='trimester',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd')], max_length=10, null=True),
        ),
    ]
