# Generated by Django 3.1.7 on 2021-03-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20210307_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolcoordinator',
            name='dob',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
