# Generated by Django 3.0.8 on 2021-03-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20210309_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anemicadolescentgirl',
            name='heightunit',
            field=models.CharField(choices=[('feet', 'feet'), ('inches', 'inches'), ('cms', 'cms'), ('inches', 'inches')], max_length=50),
        ),
        migrations.AlterField(
            model_name='anemicadolescentgirl',
            name='hipunit',
            field=models.CharField(choices=[('cms', 'cms'), ('inches', 'inches')], max_length=20),
        ),
        migrations.AlterField(
            model_name='anemicadolescentgirl',
            name='waistunit',
            field=models.CharField(choices=[('cms', 'cms'), ('inches', 'inches')], max_length=20),
        ),
        migrations.AlterField(
            model_name='anemiclactatingmother',
            name='heightunit',
            field=models.CharField(choices=[('feet', 'feet'), ('inches', 'inches'), ('cms', 'cms'), ('inches', 'inches')], max_length=50),
        ),
        migrations.AlterField(
            model_name='anemiclactatingmother',
            name='hipunit',
            field=models.CharField(choices=[('cms', 'cms'), ('inches', 'inches')], max_length=20),
        ),
        migrations.AlterField(
            model_name='anemiclactatingmother',
            name='waistunit',
            field=models.CharField(choices=[('cms', 'cms'), ('inches', 'inches')], max_length=20),
        ),
        migrations.AlterField(
            model_name='anemicpregnantwoman',
            name='heightunit',
            field=models.CharField(choices=[('feet', 'feet'), ('inches', 'inches'), ('cms', 'cms'), ('inches', 'inches')], max_length=50),
        ),
        migrations.AlterField(
            model_name='anemicpregnantwoman',
            name='hipunit',
            field=models.CharField(choices=[('cms', 'cms'), ('inches', 'inches')], max_length=20),
        ),
        migrations.AlterField(
            model_name='anemicpregnantwoman',
            name='waistunit',
            field=models.CharField(choices=[('cms', 'cms'), ('inches', 'inches')], max_length=20),
        ),
        migrations.AlterField(
            model_name='smchild',
            name='heightunit',
            field=models.CharField(choices=[('feet', 'feet'), ('inches', 'inches'), ('cms', 'cms'), ('inches', 'inches')], max_length=50),
        ),
        migrations.AlterField(
            model_name='smchild',
            name='hipunit',
            field=models.CharField(choices=[('cms', 'cms'), ('inches', 'inches')], max_length=20),
        ),
        migrations.AlterField(
            model_name='smchild',
            name='waistunit',
            field=models.CharField(choices=[('cms', 'cms'), ('inches', 'inches')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='bmi',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='heightunit',
            field=models.CharField(choices=[('feet', 'feet'), ('inches', 'inches'), ('cms', 'cms'), ('inches', 'inches')], default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='hipunit',
            field=models.CharField(choices=[('cms', 'cms'), ('inches', 'inches')], default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='waistunit',
            field=models.CharField(choices=[('cms', 'cms'), ('inches', 'inches')], default=False, max_length=20),
        ),
    ]
