# Generated by Django 3.1.7 on 2021-03-07 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0003_schoolcoordinator_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolStudentParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(blank=True, max_length=1000)),
                ('schoolname', models.CharField(max_length=2000)),
                ('personaladdress', models.CharField(max_length=2000, null=True)),
                ('dob', models.CharField(max_length=2000, null=True)),
                ('age', models.CharField(blank=True, max_length=200)),
                ('schooladdress', models.CharField(max_length=2000, null=True)),
                ('schoolcontact', models.CharField(blank=True, max_length=1000)),
                ('education', models.CharField(blank=True, max_length=2000)),
                ('occupation', models.CharField(blank=True, max_length=2000)),
                ('annualincome', models.CharField(blank=True, max_length=1000)),
                ('schoolcoordinatorincharge', models.CharField(blank=True, max_length=1000)),
                ('foodhabits', models.CharField(blank=True, max_length=1000)),
                ('profilephoto', models.ImageField(blank=True, upload_to='images/%Y/%m/%d')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
