# Generated by Django 3.0.8 on 2021-03-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20210309_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='hipunit',
            field=models.CharField(choices=[('cms', 'cms'), ('inches', 'inches')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='waistunit',
            field=models.CharField(choices=[('cms', 'cms'), ('inches', 'inches')], max_length=20),
        ),
    ]
