# Generated by Django 3.0.8 on 2021-03-07 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0004_auto_20210307_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueid', models.CharField(max_length=50)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('age', models.CharField(max_length=50)),
                ('personalcontact', models.CharField(max_length=200)),
                ('icdsname', models.CharField(max_length=200)),
                ('icdscenteraddress', models.CharField(max_length=200)),
                ('icdscentercontact', models.CharField(max_length=200)),
                ('weight', models.IntegerField()),
                ('weightunit', models.CharField(choices=[('kgs', 'kgs'), ('lbs', 'lbs')], max_length=50)),
                ('height', models.IntegerField()),
                ('heightunit', models.CharField(choices=[('kgs', 'kgs'), ('lbs', 'lbs')], max_length=50)),
                ('bmi', models.DecimalField(decimal_places=2, max_digits=5)),
                ('waist', models.IntegerField(null=True)),
                ('waistunit', models.CharField(choices=[('kgs', 'kgs'), ('lbs', 'lbs')], max_length=20)),
                ('hip', models.IntegerField(null=True)),
                ('hipunit', models.CharField(choices=[('kgs', 'kgs'), ('lbs', 'lbs')], max_length=20)),
                ('whratio', models.IntegerField(null=True)),
                ('whratioderived', models.IntegerField(null=True)),
                ('foodhabits', models.CharField(choices=[('Vegetarian', 'Vegetarian'), ('Non-Vegetarian', 'Non-Vegetarian')], max_length=20)),
                ('uploaded_photo', models.FileField(upload_to='smchilddocuments/%Y/%m/%d')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='SMChildDetails',
        ),
    ]
