# Generated by Django 3.0.8 on 2021-03-10 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20210309_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anemicadolescentgirl',
            name='bmi',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='anemiclactatingmother',
            name='bmi',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='anemicpregnantwoman',
            name='bmi',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='smchild',
            name='bmi',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='bmi',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
