# Generated by Django 3.0.8 on 2021-03-08 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20210308_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anemiclactatingmother',
            old_name='dob',
            new_name='birthdate',
        ),
        migrations.RenameField(
            model_name='anganwadiworkersregister',
            old_name='dob',
            new_name='birthdate',
        ),
        migrations.RenameField(
            model_name='bulk_reg',
            old_name='dob',
            new_name='birthdate',
        ),
        migrations.RenameField(
            model_name='mentor',
            old_name='dob',
            new_name='birthdate',
        ),
        migrations.RenameField(
            model_name='mukhyasevika',
            old_name='dob',
            new_name='birthdate',
        ),
        migrations.RenameField(
            model_name='nutrigardenexpert',
            old_name='dob',
            new_name='birthdate',
        ),
        migrations.RenameField(
            model_name='nutritionexpert',
            old_name='dob',
            new_name='birthdate',
        ),
        migrations.RenameField(
            model_name='principalinvestigators',
            old_name='dob',
            new_name='birthdate',
        ),
        migrations.RenameField(
            model_name='projectmanager',
            old_name='dob',
            new_name='birthdate',
        ),
        migrations.RenameField(
            model_name='schoolcoordinator',
            old_name='dob',
            new_name='birthdate',
        ),
        migrations.RenameField(
            model_name='schoolstudentparent',
            old_name='dob',
            new_name='birthdate',
        ),
        migrations.RenameField(
            model_name='webgisexpert',
            old_name='dob',
            new_name='birthdate',
        ),
    ]
