# Generated by Django 2.2.12 on 2021-03-09 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20210308_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anemicadolescentgirl',
            old_name='icdscenteraddress',
            new_name='ICDScenteraddress',
        ),
        migrations.RenameField(
            model_name='anemicadolescentgirl',
            old_name='icdscentercontact',
            new_name='ICDScentercontact',
        ),
        migrations.RenameField(
            model_name='anemicadolescentgirl',
            old_name='icdsname',
            new_name='ICDSname',
        ),
        migrations.RenameField(
            model_name='anemiclactatingmother',
            old_name='icdscenteraddress',
            new_name='ICDScenteraddress',
        ),
        migrations.RenameField(
            model_name='anemiclactatingmother',
            old_name='icdscentercontact',
            new_name='ICDScentercontact',
        ),
        migrations.RenameField(
            model_name='anemiclactatingmother',
            old_name='icdsname',
            new_name='ICDSname',
        ),
        migrations.RenameField(
            model_name='anemicpregnantwoman',
            old_name='icdscenteraddress',
            new_name='ICDScenteraddress',
        ),
        migrations.RenameField(
            model_name='anemicpregnantwoman',
            old_name='icdscentercontact',
            new_name='ICDScentercontact',
        ),
        migrations.RenameField(
            model_name='anemicpregnantwoman',
            old_name='icdsname',
            new_name='ICDSname',
        ),
        migrations.RenameField(
            model_name='smchild',
            old_name='icdscenteraddress',
            new_name='ICDScenteraddress',
        ),
        migrations.RenameField(
            model_name='smchild',
            old_name='icdscentercontact',
            new_name='ICDScentercontact',
        ),
        migrations.RenameField(
            model_name='smchild',
            old_name='icdsname',
            new_name='ICDSname',
        ),
        migrations.RenameField(
            model_name='smchildparentsregister',
            old_name='icdscenteraddress',
            new_name='ICDScenteraddress',
        ),
        migrations.RenameField(
            model_name='smchildparentsregister',
            old_name='icdscentercontact',
            new_name='ICDScentercontact',
        ),
        migrations.RenameField(
            model_name='smchildparentsregister',
            old_name='icdsname',
            new_name='ICDSname',
        ),
    ]
