# Generated by Django 3.0.8 on 2021-03-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20210307_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bmi',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=5),
        ),
        migrations.AddField(
            model_name='student',
            name='height',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='heightunit',
            field=models.CharField(choices=[('kgs', 'kgs'), ('lbs', 'lbs')], default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='hip',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='hipunit',
            field=models.CharField(choices=[('kgs', 'kgs'), ('lbs', 'lbs')], default=False, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='waist',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='waistunit',
            field=models.CharField(choices=[('kgs', 'kgs'), ('lbs', 'lbs')], default=False, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='weight',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='weightunit',
            field=models.CharField(choices=[('kgs', 'kgs'), ('lbs', 'lbs')], default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='whratio',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='whratioderived',
            field=models.IntegerField(null=True),
        ),
    ]
