# Generated by Django 2.2.12 on 2021-03-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_auto_20210310_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anemicadolescentgirl',
            name='heightunit',
            field=models.CharField(choices=[('feet', 'feet'), ('inches', 'inches'), ('cms', 'cms'), ('inches', 'inches')], max_length=50),
        ),
        migrations.AlterField(
            model_name='anemicadolescentgirl',
            name='whratio',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='anemiclactatingmother',
            name='heightunit',
            field=models.CharField(choices=[('feet', 'feet'), ('inches', 'inches'), ('cms', 'cms'), ('inches', 'inches')], max_length=50),
        ),
        migrations.AlterField(
            model_name='anemiclactatingmother',
            name='whratio',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='anemicpregnantwoman',
            name='heightunit',
            field=models.CharField(choices=[('feet', 'feet'), ('inches', 'inches'), ('cms', 'cms'), ('inches', 'inches')], max_length=50),
        ),
        migrations.AlterField(
            model_name='anemicpregnantwoman',
            name='whratio',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mukhyasevika',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mukhyasevika',
            name='contact',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='schoolstudentparent',
            name='contact',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='schoolstudentparent',
            name='personaladdress',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='schoolstudentparent',
            name='schoolname',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='smchild',
            name='heightunit',
            field=models.CharField(choices=[('feet', 'feet'), ('inches', 'inches'), ('cms', 'cms'), ('inches', 'inches')], max_length=50),
        ),
        migrations.AlterField(
            model_name='smchild',
            name='whratio',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='heightunit',
            field=models.CharField(choices=[('feet', 'feet'), ('inches', 'inches'), ('cms', 'cms'), ('inches', 'inches')], default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='uid',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='whratio',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, null=True),
        ),
    ]
