# Generated by Django 2.2.12 on 2021-03-15 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_auto_20210312_0705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.RemoveField(
            model_name='student',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='student',
            name='bmi',
        ),
        migrations.RemoveField(
            model_name='student',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='student',
            name='height',
        ),
        migrations.RemoveField(
            model_name='student',
            name='heightunit',
        ),
        migrations.RemoveField(
            model_name='student',
            name='hip',
        ),
        migrations.RemoveField(
            model_name='student',
            name='hipunit',
        ),
        migrations.RemoveField(
            model_name='student',
            name='schooladdress',
        ),
        migrations.RemoveField(
            model_name='student',
            name='schoolcontactinformation',
        ),
        migrations.RemoveField(
            model_name='student',
            name='schoolcordinatorincharge',
        ),
        migrations.RemoveField(
            model_name='student',
            name='schoolname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='uploaded_photo',
        ),
        migrations.RemoveField(
            model_name='student',
            name='waist',
        ),
        migrations.RemoveField(
            model_name='student',
            name='waistunit',
        ),
        migrations.RemoveField(
            model_name='student',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='student',
            name='weightunit',
        ),
        migrations.RemoveField(
            model_name='student',
            name='whratio',
        ),
        migrations.RemoveField(
            model_name='student',
            name='whratioderived',
        ),
    ]
