# Generated by Django 3.1.1 on 2021-02-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdolescentGirlsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=2000)),
                ('weight', models.IntegerField()),
                ('weightunit', models.CharField(max_length=20)),
                ('height', models.IntegerField()),
                ('heightunit', models.CharField(max_length=20)),
                ('bmi', models.IntegerField()),
                ('age', models.IntegerField()),
                ('hemoglobinvalue', models.DecimalField(decimal_places=2, max_digits=4)),
                ('date', models.DateField()),
                ('recommendedfood', models.CharField(max_length=2000)),
                ('complication', models.CharField(max_length=2000)),
                ('education', models.CharField(max_length=2000)),
                ('medication', models.CharField(max_length=2000)),
                ('healthparameters', models.CharField(max_length=2000)),
                ('medicaladvice', models.CharField(max_length=2000)),
                ('uploaddocuments', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('deedback', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='BodyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('weightunit', models.CharField(max_length=20)),
                ('height', models.IntegerField()),
                ('heightunit', models.CharField(max_length=20)),
                ('bmi', models.IntegerField()),
                ('waist', models.IntegerField()),
                ('waistunit', models.CharField(max_length=20)),
                ('hip', models.IntegerField()),
                ('hipunit', models.CharField(max_length=20)),
                ('whratio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DailyScheduleForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleepfrom', models.TimeField()),
                ('sleepto', models.TimeField()),
                ('eatfrom', models.TimeField()),
                ('eatto', models.TimeField()),
                ('studyfrom', models.TimeField()),
                ('studyto', models.TimeField()),
                ('playfrom', models.TimeField()),
                ('playto', models.TimeField()),
                ('housework', models.CharField(max_length=500)),
                ('activities', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='DietModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mealtype', models.CharField(max_length=200)),
                ('timefrom', models.TimeField()),
                ('timeto', models.TimeField()),
                ('rotiquantity', models.IntegerField(blank=True, default=0, null=True)),
                ('rotiunit', models.CharField(blank=True, max_length=200, null=True)),
                ('ricequantity', models.IntegerField(blank=True, default=0, null=True)),
                ('riceunit', models.CharField(blank=True, max_length=200, null=True)),
                ('pohaquantity', models.IntegerField(blank=True, default=0, null=True)),
                ('pohaunit', models.CharField(blank=True, max_length=200, null=True)),
                ('upmaquantity', models.IntegerField(blank=True, default=0, null=True)),
                ('upmaunit', models.CharField(blank=True, max_length=200, null=True)),
                ('teaquantity', models.IntegerField(blank=True, default=0, null=True)),
                ('teaunit', models.CharField(blank=True, max_length=200, null=True)),
                ('coffeequantity', models.IntegerField(blank=True, default=0, null=True)),
                ('coffeeunit', models.CharField(blank=True, max_length=200, null=True)),
                ('milkquantity', models.IntegerField(blank=True, default=0, null=True)),
                ('milkunit', models.CharField(blank=True, max_length=200, null=True)),
                ('vadaquantity', models.IntegerField(blank=True, default=0, null=True)),
                ('biscuitquantity', models.IntegerField(blank=True, default=0, null=True)),
                ('dalquantity', models.IntegerField(blank=True, default=0, null=True)),
                ('dalunit', models.CharField(blank=True, max_length=200, null=True)),
                ('gujratidalquantity', models.IntegerField(blank=True, default=0, null=True)),
                ('gujratidalunit', models.CharField(blank=True, max_length=200, null=True)),
                ('toordalquantity', models.IntegerField(blank=True, default=0, null=True)),
                ('toordalunit', models.CharField(blank=True, max_length=200, null=True)),
                ('moongdalquantity', models.IntegerField(blank=True, default=0, null=True)),
                ('moongdalunit', models.CharField(blank=True, max_length=200, null=True)),
                ('palakquantity', models.IntegerField(blank=True, default=0, null=True)),
                ('palakunit', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EatTodayModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodhabbits', models.CharField(max_length=200)),
                ('foodallergies', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('issues', models.TextField(max_length=2000)),
                ('suggestions', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInformationForms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueid', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('year', models.CharField(max_length=4)),
                ('month', models.CharField(max_length=2)),
                ('days', models.CharField(max_length=2)),
                ('fathername', models.CharField(max_length=200)),
                ('mothername', models.CharField(max_length=200)),
                ('contactnumber', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('profileimage', models.ImageField(upload_to='profileimages/%Y/%m/%d')),
            ],
        ),
    ]
