# Generated by Django 2.2.12 on 2021-03-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprof',
            name='uploaded_photo',
            field=models.ImageField(upload_to='studentpp/%Y/%m/%d'),
        ),
    ]
