# Generated by Django 2.2.12 on 2021-03-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_feed', '0003_auto_20210303_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyscheduleform',
            name='activity',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dietmodel',
            name='recipe',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bodymodel',
            name='bmi',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bodymodel',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bodymodel',
            name='hip',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bodymodel',
            name='waist',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bodymodel',
            name='weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bodymodel',
            name='whratio',
            field=models.IntegerField(null=True),
        ),
    ]
