# Generated by Django 3.0.8 on 2021-03-31 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_feed', '0005_generalinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocioDemographicModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_live_with', models.CharField(blank=True, choices=[('My parents', 'My parents'), ('My parents and siblings', 'My parents and siblings'), ('My parents, siblings and grandparents', 'My parents, siblings and grandparents'), ('My parents, siblings, grandparents, aunts, uncles and cousins', 'My parents, siblings, grandparents, aunts, uncles and cousins'), ('Others', 'Others')], max_length=100)),
                ('number_of_family_members', models.CharField(blank=True, max_length=100)),
                ('name_of_the_guardian', models.CharField(blank=True, max_length=100)),
                ('age_of_the_guardian', models.CharField(blank=True, max_length=100)),
                ('education_of_the_guardian', models.CharField(blank=True, choices=[('Professional degree (Post graduate)', 'Professional degree (Post graduate)'), ('Graduate (Bachelors)', 'Graduate (Bachelors)'), ('Higher Secondary certificate (12th Std)', 'Higher Secondary certificate (12th Std)'), ('Secondary school certificate (SSC - 10th Std)', 'Secondary school certificate (SSC - 10th Std)'), ('Middle school (5th to 10th std)', 'Middle school (5th to 10th std)'), ('Primary school (1st to 4th std)', 'Primary school (1st to 4th std)'), ('Illiterate (No education)', 'Illiterate (No education)'), ('Other', 'Other')], max_length=100)),
                ('occupation_of_the_guardian', models.CharField(blank=True, choices=[('Accountants', 'Accountants'), ('Administrative Assistants', 'Administrative Assistants'), ('Advocates', 'Advocates'), ('Anganwadi Worker', 'Anganwadi Worker'), ('Architects', 'Architects'), ('Assemblers', 'Assemblers'), ('Auditors', 'Auditors'), ('Business Person', 'Business Person'), ('Cleaners (Washing Windows And Other Glass Surfaces Of Buildings)', 'Cleaners (Washing Windows And Other Glass Surfaces Of Buildings)'), ('College Principals', 'College Principals'), ('Commercial Truck Drivers', 'Commercial Truck Drivers'), ('Cooks', 'Cooks'), ('Craftsmen', 'Craftsmen'), ('Crane Operators', 'Crane Operators'), ('Doctors', 'Doctors'), ('Engineers', 'Engineers'), ('Expert Musicians', 'Expert Musicians'), ('Farmers', 'Farmers'), ('Fishermen', 'Fishermen'), ('Garbage Collector', 'Garbage Collector'), ('General Office Clerks', 'General Office Clerks'), ('Housekeeper/ Housemaid (Hotels/ House)', 'Housekeeper/ Housemaid (Hotels/ House)'), ('Lecturers', 'Lecturers'), ('Mechanist', 'Mechanist'), ('Newspaper Editors', 'Newspaper Editors'), ('Nurse', 'Nurse'), ('Office Assistants', 'Office Assistants'), ('Paramedics', 'Paramedics'), ('Plant And Machine Operators', 'Plant And Machine Operators'), ('Plumbers', 'Plumbers'), ('Police Officers', 'Police Officers'), ('Reading And Emptying Meters', 'Reading And Emptying Meters'), ('Receptionists', 'Receptionists'), ('Retired', 'Retired'), ('Salesman', 'Salesman'), ('Scientists', 'Scientists'), ('Security Guard (Housing Societies/Company/Banks/Land)', 'Security Guard (Housing Societies/Company/Banks/Land)'), ('Senior Administrative Officers', 'Senior Administrative Officers'), ('Software Development', 'Software Development'), ('Soldiers', 'Soldiers'), ('Stocking Vending Machines', 'Stocking Vending Machines'), ('Street Vendor', 'Street Vendor'), ('Sweeper', 'Sweeper'), ('Unemployed', 'Unemployed'), ('OTHERS', 'OTHERS')], max_length=300)),
                ('monthly_family_income', models.CharField(blank=True, choices=[('>199,862', '>199,862'), ('99,931-199,861', '99,931-199,861'), ('74,755-99,930', '74,755-99,930'), ('49,962-74,755', '49,962-74,755'), ('29,973-49,961', '29,973-49,961'), ('10,002-29,97', '10,002-29,97'), ('< 10,001', '< 10,001')], max_length=100)),
                ('ration_card_color_is', models.CharField(blank=True, choices=[('Red color', 'Red color'), ('Orange color', 'Orange color'), ('White color', 'White color'), ('No ration card', 'No ration card')], max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='anemicadolescentgirlprof',
            name='annualincome',
            field=models.CharField(choices=[('>199,862', '>199,862'), ('99,931-199,861', '99,931-199,861'), ('74,755-99,930', '74,755-99,930'), ('49,962-74,755', '49,962-74,755'), ('29,973-49,961', '29,973-49,961'), ('10,002-29,97', '10,002-29,97'), ('< 10,001', '< 10,001')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='anemiclactatingmotherprof',
            name='annualincome',
            field=models.CharField(choices=[('>199,862', '>199,862'), ('99,931-199,861', '99,931-199,861'), ('74,755-99,930', '74,755-99,930'), ('49,962-74,755', '49,962-74,755'), ('29,973-49,961', '29,973-49,961'), ('10,002-29,97', '10,002-29,97'), ('< 10,001', '< 10,001')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='awprof',
            name='annualincome',
            field=models.CharField(blank=True, choices=[('>199,862', '>199,862'), ('99,931-199,861', '99,931-199,861'), ('74,755-99,930', '74,755-99,930'), ('49,962-74,755', '49,962-74,755'), ('29,973-49,961', '29,973-49,961'), ('10,002-29,97', '10,002-29,97'), ('< 10,001', '< 10,001')], max_length=25500),
        ),
        migrations.AlterField(
            model_name='msprof',
            name='annualincome',
            field=models.CharField(blank=True, choices=[('>199,862', '>199,862'), ('99,931-199,861', '99,931-199,861'), ('74,755-99,930', '74,755-99,930'), ('49,962-74,755', '49,962-74,755'), ('29,973-49,961', '29,973-49,961'), ('10,002-29,97', '10,002-29,97'), ('< 10,001', '< 10,001')], max_length=25500),
        ),
        migrations.AlterField(
            model_name='pregnantwomanprof',
            name='annualincome',
            field=models.CharField(choices=[('>199,862', '>199,862'), ('99,931-199,861', '99,931-199,861'), ('74,755-99,930', '74,755-99,930'), ('49,962-74,755', '49,962-74,755'), ('29,973-49,961', '29,973-49,961'), ('10,002-29,97', '10,002-29,97'), ('< 10,001', '< 10,001')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scprof',
            name='annualincome',
            field=models.CharField(blank=True, choices=[('>199,862', '>199,862'), ('99,931-199,861', '99,931-199,861'), ('74,755-99,930', '74,755-99,930'), ('49,962-74,755', '49,962-74,755'), ('29,973-49,961', '29,973-49,961'), ('10,002-29,97', '10,002-29,97'), ('< 10,001', '< 10,001')], max_length=25500),
        ),
        migrations.AlterField(
            model_name='smparentsprof',
            name='annualincome',
            field=models.CharField(blank=True, choices=[('>199,862', '>199,862'), ('99,931-199,861', '99,931-199,861'), ('74,755-99,930', '74,755-99,930'), ('49,962-74,755', '49,962-74,755'), ('29,973-49,961', '29,973-49,961'), ('10,002-29,97', '10,002-29,97'), ('< 10,001', '< 10,001')], max_length=25500),
        ),
    ]
