# Generated by Django 3.0.8 on 2021-03-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_feed', '0006_auto_20210331_0647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sociodemographicmodel',
            old_name='age_of_the_guardian',
            new_name='guardian_age',
        ),
        migrations.RenameField(
            model_name='sociodemographicmodel',
            old_name='name_of_the_guardian',
            new_name='guardian_name',
        ),
        migrations.RenameField(
            model_name='sociodemographicmodel',
            old_name='occupation_of_the_guardian',
            new_name='guardian_occupation',
        ),
        migrations.RenameField(
            model_name='sociodemographicmodel',
            old_name='ration_card_color_is',
            new_name='ration_card_color',
        ),
        migrations.RemoveField(
            model_name='sociodemographicmodel',
            name='education_of_the_guardian',
        ),
        migrations.AddField(
            model_name='sociodemographicmodel',
            name='guardian_education',
            field=models.CharField(blank=True, choices=[('Professional degree (Post graduate)', 'Professional degree (Post graduate)'), ('Graduate (Bachelors)', 'Graduate (Bachelors)'), ('Higher Secondary certificate (12th Std)', 'Higher Secondary certificate (12th Std)'), ('Secondary school certificate (SSC - 10th Std)', 'Secondary school certificate (SSC - 10th Std)'), ('Middle school (5th to 10th std)', 'Middle school (5th to 10th std)'), ('Primary school (1st to 4th std)', 'Primary school (1st to 4th std)'), ('Illiterate (No education)', 'Illiterate (No education)'), ('Other', 'Other')], max_length=100),
        ),
    ]
