# Generated by Django 3.0.8 on 2021-01-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DemoDiet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('issues', models.TextField()),
                ('suggestions', models.TextField()),
            ],
        ),
    ]
