# Generated by Django 3.0.8 on 2021-01-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DemoDiet', '0002_feedbackmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmodel',
            name='issues',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='suggestions',
            field=models.TextField(max_length=2000),
        ),
    ]
