# Generated by Django 3.0.8 on 2021-01-08 05:42

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('DemoDiet', '0003_auto_20210107_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contact',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=1000)),
        ),
    ]
