<<<<<<< HEAD
# Generated by Django 3.1.5 on 2021-03-31 04:51
=======
# Generated by Django 3.0.8 on 2021-03-23 06:38
>>>>>>> 97f532dadca856a2f108235854001be68d4cbc17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True)),
                ('Document', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='document_icds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True)),
                ('document', models.FileField(default=False, upload_to='document_icds/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='document_nutri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True)),
                ('document', models.FileField(default=False, upload_to='document_nutri/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='document_sch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True)),
                ('document', models.FileField(default=False, upload_to='document_school/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='image_up',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True)),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='image_up_icds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True)),
                ('image', models.ImageField(default=False, upload_to='image_icds/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='image_up_nutri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True)),
                ('image', models.ImageField(default=False, upload_to='image_nutri/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='image_up_sch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True)),
                ('image', models.ImageField(default=False, upload_to='image_school/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='video_icds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True)),
                ('video', models.FileField(default=False, upload_to='video_icds/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='video_nutri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True)),
                ('video', models.FileField(default=False, upload_to='video_nutri/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='video_sch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True)),
                ('video', models.FileField(default=False, upload_to='video_school/%Y/%m/%d')),
            ],
        ),
    ]
