# Generated by Django 3.0.8 on 2021-03-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='document_icds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True)),
                ('document', models.FileField(default=False, upload_to='document_icds/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='document_nutri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True)),
                ('document', models.FileField(default=False, upload_to='document_nutri/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='document_sch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True)),
                ('document', models.FileField(default=False, upload_to='document_school/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='image_up_icds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True)),
                ('image', models.ImageField(default=False, upload_to='image_icds/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='image_up_nutri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True)),
                ('image', models.ImageField(default=False, upload_to='image_nutri/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='image_up_sch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True)),
                ('image', models.ImageField(default=False, upload_to='image_school/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='video_icds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True)),
                ('video', models.FileField(default=False, upload_to='video_icds/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='video_nutri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True)),
                ('video', models.FileField(default=False, upload_to='video_nutri/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='video_sch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True)),
                ('video', models.FileField(default=False, upload_to='video_school/%Y/%m/%d')),
            ],
        ),
    ]
